// build.js — runs at Vercel deploy time (or any CI).
// Reads GH_TOKEN from the environment and writes env.js into the output.
// Locally, just edit env.js directly (it's gitignored).

const fs = require('fs');
const path = require('path');

const token = process.env.GH_TOKEN || '';

const content = `// Auto-generated by build.js — do not edit by hand.
window.__ENV__ = {
  GH_TOKEN: ${JSON.stringify(token)},
};
`;

fs.writeFileSync(path.join(__dirname, 'env.js'), content, 'utf8');
console.log(`[build] env.js written. GH_TOKEN ${token ? 'is SET ✓' : 'is EMPTY (unauthenticated mode)'}`);
